# -*- coding: utf-8 -*-
"""analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYpA8PcTuqSuoM1huIFwPni9YNTVdz3Z
"""

# src/analysis.py
from __future__ import annotations
import pandas as pd
from src.cleaning import normalize_zip

def vacancies_by_zip(vacant_df: pd.DataFrame, zip_col: str = "zip") -> pd.DataFrame:
    df = normalize_zip(vacant_df, zip_col)
    if zip_col not in df.columns:
        return pd.DataFrame(columns=["zip", "vacant_count"])
    out = (
        df.groupby(zip_col, dropna=False)
          .size()
          .reset_index(name="vacant_count")
          .rename(columns={zip_col: "zip"})
          .sort_values("vacant_count", ascending=False)
    )
    return out

def snow_records_by_zip(snow_df: pd.DataFrame, zip_col: str = "zip") -> pd.DataFrame:
    df = normalize_zip(snow_df, zip_col)
    if zip_col not in df.columns:
        return pd.DataFrame(columns=["zip", "snow_records"])
    out = (
        df.groupby(zip_col, dropna=False)
          .size()
          .reset_index(name="snow_records")
          .rename(columns={zip_col: "zip"})
          .sort_values("snow_records", ascending=False)
    )
    return out

def merge_vacancy_and_snow(v_by_zip: pd.DataFrame, s_by_zip: pd.DataFrame) -> pd.DataFrame:
    merged = v_by_zip.merge(s_by_zip, on="zip", how="left")
    merged["snow_records"] = merged["snow_records"].fillna(0).astype(int)
    return merged