# -*- coding: utf-8 -*-
"""cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1984_5jIqiQit-TmkWEJOyvcPSbX6-NRq
"""

# src/cleaning.py
from __future__ import annotations
import re
import pandas as pd

def standardize_column_names(df: pd.DataFrame) -> pd.DataFrame:
    renamed = {}
    for c in df.columns:
        clean = c.strip().lower()
        clean = re.sub(r"[^a-z0-9]+", "_", clean)
        clean = re.sub(r"_+", "_", clean).strip("_")
        renamed[c] = clean
    return df.rename(columns=renamed)

def normalize_zip(df: pd.DataFrame, col: str = "zip") -> pd.DataFrame:
    out = df.copy()
    if col not in out.columns:
        return out
    out[col] = (
        out[col]
        .astype(str)
        .str.extract(r"(\d{5})", expand=False)
    )
    return out

def coerce_datetime(df: pd.DataFrame, col: str) -> pd.DataFrame:
    out = df.copy()
    if col in out.columns:
        out[col] = pd.to_datetime(out[col], errors="coerce")
    return out