# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1qC1NbVdjnzybgzVfpn4Lq5RfGoEHMl
"""

# src/config.py
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Paths:
    root: Path
    raw: Path
    processed: Path
    outputs_reports: Path
    outputs_figures: Path


def get_paths() -> Paths:
    root = Path(__file__).resolve().parents[1]
    return Paths(
        root=root,
        raw=root / "data" / "raw",
        processed=root / "data" / "processed",
        outputs_reports=root / "outputs" / "reports",
        outputs_figures=root / "outputs" / "figures",
    )


@dataclass(frozen=True)
class Dataset:
    name: str
    soda_domain: str
    resource_id: str
    file_stem: str


def datasets() -> list[Dataset]:
    """
    Replace resource_id with the actual dataset IDs from data.syr.gov
    (the 4x4 Socrata IDs, e.g., 'abcd-1234').

    Tip: open a dataset page -> API -> copy the identifier.
    """
    return [
        Dataset(
            name="Vacant Properties",
            soda_domain="data.syr.gov",
            resource_id="REPLACE_ME",   # e.g., "xxxx-xxxx"
            file_stem="vacant_properties",
        ),
        Dataset(
            name="Snow Plow Routes / Winter Service",
            soda_domain="data.syr.gov",
            resource_id="REPLACE_ME",   # e.g., "yyyy-yyyy"
            file_stem="snow_routes",
        ),
    ]


DEFAULT_ROW_LIMIT = 200000  # keep sane; increase if needed
USER_AGENT = "syracuse-civic-project (contact: neha)"