# -*- coding: utf-8 -*-
"""io.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAPBByE17e1BxouH_Yckx_H7al-ywRpX
"""

import sys
from pathlib import Path

# walk upward until we find the project root that contains `src/`
p = Path.cwd().resolve()
while p != p.parent and not (p / "src").exists():
    p = p.parent

sys.path.insert(0, str(p))