# -*- coding: utf-8 -*-
"""phase4_generate_docs.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbrLTqYL2HIYfbbKN3x3kBaNNWVy9Ivq
"""

# scripts/phase4_generate_docs.py
from __future__ import annotations
from pathlib import Path
from datetime import date

def write(path: Path, txt: str) -> None:
    path.write_text(txt.strip() + "\n", encoding="utf-8")

def main() -> None:
    root = Path(__file__).resolve().parents[1]

    readme = f"""
# Syracuse Open Data Civic Project

Created: {date.today().isoformat()}

## What this is
A reproducible pipeline that produces:
- cleaned datasets
- validated tables (“ground truth” checks)
- charts + reports

## Run
```bash
python scripts/phase4_run_all.py
pytest -q

"""