# -*- coding: utf-8 -*-
"""validation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11egcOXXX0kkeh6HgcIN5f3_VwFbVQfQs
"""

# src/validation.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Callable
import pandas as pd

@dataclass(frozen=True)
class Check:
    name: str
    passed: bool
    details: str

def require_cols(df: pd.DataFrame, cols: list[str], name: str) -> Check:
    missing = [c for c in cols if c not in df.columns]
    return Check(name, len(missing) == 0, "OK" if not missing else f"Missing: {missing}")

def non_empty(df: pd.DataFrame, name: str) -> Check:
    return Check(name, df.shape[0] > 0, f"rows={df.shape[0]}" if df.shape[0] > 0 else "EMPTY")

def claim(name: str, fn: Callable[[], bool], fail_msg: str) -> Check:
    try:
        ok = bool(fn())
        return Check(name, ok, "OK" if ok else fail_msg)
    except Exception as e:
        return Check(name, False, f"ERROR: {e}")

def to_df(checks: list[Check]) -> pd.DataFrame:
    return pd.DataFrame([{"check": c.name, "passed": c.passed, "details": c.details} for c in checks])