# -*- coding: utf-8 -*-
"""viz.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCP9bGVDQXZNSfNI0NRvEXSgT8xnf1JF
"""

from __future__ import annotations
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd

def bar_top10(df: pd.DataFrame, x: str, y: str, title: str, outpath: Path) -> None:
    top = df.head(10).copy()
    plt.figure()
    plt.bar(top[x].astype(str), top[y])
    plt.title(title)
    plt.xlabel(x)
    plt.ylabel(y)
    plt.xticks(rotation=45, ha="right")
    outpath.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(outpath, dpi=200)
    plt.close()